spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: adsds126@gmail.com
    password: ${SMTP_CREDENTIALS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: